Code review
BenFin75/JSCalculator pull request #1
Opened 2022-01-04 22:52 UTC by BenFin75

2022-01-04 22:53 UTC, jwsharpe requested changes

2022-01-04 22:53 UTC, jwsharpe commented on index.html
> +<body>
I can leave reviews like this now

2022-01-04 22:54 UTC, BenFin75 commented on index.html
> +<body>
wild

2022-01-05 03:06 UTC, jwsharpe requested changes
A couple things to think about:

In general one of the most important things to do when coding a software project is to ask yourself what is the scope of the work I'm trying to accomplish? and, how is the scope likely to change and does my code account for that? 

For instance what if we wanted to adapt the code to cover parentheses, or we wanted to add more trigonometric functions?
    Could that be easily added?
    How would the code change?

If you're maintaining code or adding new features its something that needs to be asked every time, but that's something that is more down the pipeline from where you're at


Me saying things like "not having global variables" or "linking the ui and backend is bad" is not necessarily a fact of code, but these things are flags to me to write programs in a more structured way, having opinionated code could help you tackle the above problem down the line.

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +let numberOne = "NaN";
in general global variables should be avoided

there are ways to write this code without the need

but this isn't the worst use of globals either.

You obviously need statefulness for a calculator, but some of these variables can be avoided by working with a smaller set of global variables and calculating everything. There are also probably smarter ways to set this up. 

I think the minimum set of variables you would need is just
```previousNum, operation``` 

and if you're feeling particularly spicy, just make a stack of operations and save all of them
```opSet``` = `[{num, op}, {num, op}...]`

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +                answer = "You can't do that!"
lmao

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +    operator = undefined;
without global vars this can be avoided,

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +let finished = 0;
can't this just be a boolean?

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +    console.log(`output: ${output}`);
quick trick for this, but you can just write `console.log({output})` and it'll give you a nice log

2022-01-05 03:06 UTC, jwsharpe commented on style.css
> +body {
are you forced to use `css`? There are other types of things that can compile into css which are fun to look at. 
Probably not worth looking at if they expect you to do this.

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +    const input  = e.target.textContent;
i see why you want this and it's a neat way to link the UI to the backend,
but in general you might want to avoid linking UI logic and backend logic together like this.

by attaching these together you make it harder to edit later if you have to make any changes.

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +        operations.forEach(operation => operation.removeEventListener('click', getInput))
It's technically better form to just block the action going through, rather then just removing the event listener. 
It just gives you more flexibility later on.

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +            //convert into a percent, idk most calculators have this, seems not very useful
lmao ew

2022-01-05 03:06 UTC, jwsharpe commented on script.js
> +                break;
technically don't need a break here but w/e

2022-01-05 03:17 UTC, BenFin75 commented on style.css
> +body {
SCSS

2022-01-05 16:06 UTC, merged